### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Tigerly** [nsumner/llvm-dataflow-analysis#1]
Hello, I'm a LLVM beginner. I'm trying to build this project. However, it is failed on my machine(OS: ubuntu).
Would it be possible to take a look at the error infos below (I use clang-4.0 to compile)?
Thanks in advance!

llvm-dataflow-analysis/include/DataflowAnalysis.h:215:12: error: expected unqualified-id before ‘[’ token
       auto [context, function] = contextWork.take();
            ^
/llvm-dataflow-analysis/include/DataflowAnalysis.h:216:31: error: ‘function’ was not declared in this scope
       computeForwardDataflow(*function, context);
...

**Comment by nsumner** [comment]
That will happen if the building compiler does not have c++17 support. You can see the compiler being used at the top of the cmake printout.

You can explicitly set the compiler:

    cmake -DCMAKE_CXX_COMPILER=clang++  <... same as before ...>
